version: '3'
services:
  bot:
    image: bot
    build:
      context: ./
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    extra_hosts:
      - "host.docker.internal:host-gateway"